version: '2.2'
services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./app:/usr/share/nginx/html
  chromedriver:
    image: victoriza/chromedriver:1.5
    environment:
      - VNC_ENABLED=true
      - EXPOSE_X11=true
    ports:
      - 5900:5900
  nightwatch:
    image: victoriza/s.vimes:1.0
    init: true
    depends_on:
      - chromedriver
      - nginx
    environment:
      - WAIT_FOR_HOSTS=nginx:80 chromedriver:4444 chromedriver:6060
    volumes:
      - ./test:/home/node
